# Generated by Django 3.1 on 2020-08-19 20:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20200818_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='wishlist_users',
            field=models.ManyToManyField(blank=True, related_name='wishlist_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
