# Generated by Django 3.1 on 2020-09-08 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20200907_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
