# Generated by Django 3.1 on 2020-08-21 17:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20200819_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='watchlist_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
