# Generated by Django 3.1 on 2020-08-21 18:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_listing_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='users', to=settings.AUTH_USER_MODEL),
        ),
    ]
